version: "3"

services:
    app:
        build:
            args:
                user: archive
                uid: 1000
            context: ./
            dockerfile: docker-compose/Dockerfile
        image: php
        container_name: archive_php
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
            - ./docker-compose/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - archive

    supervisor:
        build:
            args:
                user: archive
                uid: 1000
            context: ./
            dockerfile: docker-compose/Supervisor.Dockerfile
        image: supervisor
        container_name: archive_supervisor
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
            - ./docker-compose/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - archive

    postgres:
        image: postgres:latest
        container_name: archive_postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            PGDATA: /data/postgres
        volumes:
            - postgres:/data/postgres
        ports:
            - "5432:5432"
        networks:
            - archive
        restart: unless-stopped

    nginx:
        image: nginx:latest
        container_name: archive_nginx
        restart: unless-stopped
        ports:
            - "8999:8999"
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - archive

#    supervisor:
#        image: redditsaved/laravel-supervisord:latest
#        container_name: archive_supervisor
#        restart: unless-stopped
#        networks:
#            - archive
#        depends_on:
#            - app
#            - nginx
#        command: supervisord

networks:
    archive:
        driver: bridge

volumes:
    postgres:
